version: "2"

services:
  nctl-container:
    build:
      context: ./nctl-container
      dockerfile: Dockerfile
    ports:
    - "5001:11101"
    - "4000:4000"
    networks:
      - fondant-network
    environment:
      PREDEFINED_ACCOUNTS: "true"
      DEPLOY_DELAY: "5sec"

  lean-api:
    build:
      context: ./lean-api
      dockerfile:
        Dockerfile
    ports:
      - "3000:3000" # Expose the lean API on port 3000
    networks:
      - fondant-network

  react-app: 
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    networks:
      - fondant-network

networks:
  fondant-network:
