version: "2.1"

services:
  fondant-cctl-container:
    build:
      context: ./cctl-container
      dockerfile: Dockerfile
      args:
        NODE_GITBRANCH: release-1.5.6
        CLIENT_GITBRANCH: release-2.0.0
    ports:
      - "3001:3001"
      - "80:80"
    

  fondant-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    

volumes:
  app-volume: