version: "2.1"

services:
  fondant-cctl-container:
    build:
      context: ./cctl-container
      dockerfile: Dockerfile.dev
      args:
        NODE_GITBRANCH: release-1.5.6
        CLIENT_GITBRANCH: release-2.0.0
    ports:
      - "3001:3001"
      - "80:80"
    environment:
      - PROXY_PORT=80
    networks:
      - fondant-network

  fondant-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    networks:
      - fondant-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  fondant-network:
    driver: bridge

volumes:
  app-volume:
