FROM commondrum/cctl-fondant:latest

USER root

RUN apt-get update && \
    apt-get install -y nginx curl && \
    rm -rf /var/lib/apt/lists/*

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR /usr/src/myapp

COPY api/Cargo.toml ./
COPY api/Rocket.toml ./
COPY api/src ./src

RUN cargo build --release

WORKDIR /usr/local/bin

RUN cp /usr/src/myapp/target/release/api ./
COPY api/src/commands.json ./

RUN chmod -R +x /home/cctl

ENTRYPOINT ["/usr/local/bin/api"]

EXPOSE 3001 80

CMD ["tail", "-f", "/dev/null"]